kind: Deployment
apiVersion: apps/v1
metadata:
  name: signalrchat-app
  labels:
    app: signalrchat-app
    ver: 1.4.0
spec:
 replicas: 1
 selector:
   matchLabels:
     app: signalrchat-app
 template:
    metadata:
      labels:
        app: signalrchat-app
    spec:
      containers:
        - name: signalrchat-app
          image: image-registry.openshift-image-registry.svc:5000/signalrchat-app-pipeline/signalrchat:1.4.0
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 256Mi
