kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-deployer
rules:
  - verbs:
      - create
      - get
      - watch
      - list
      - patch
    apiGroups:
      - ''
    resources:
      - pods
      - deployments
      - services
  - verbs:
      - create
      - get
      - watch
      - list
      - patch
    apiGroups:
      - route.openshift.io
    resources:
      - routes
  - verbs:
      - create
      - get
      - watch
      - list
      - patch
    apiGroups:
      - apps
    resources:
      - deployments
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-deployer-all-namespace
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: signalrchat-app-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipeline-deployer
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-image-pusher
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: signalrchat-app-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-pusher'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: signalrchat-app-dev-image-puller
  namespace: signalrchat-app-pipeline
subjects:
  - kind: ServiceAccount
    name: default
    namespace: signalrchat-app-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-puller'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: signalrchat-app-uat-image-puller
  namespace: signalrchat-app-pipeline
subjects:
  - kind: ServiceAccount
    name: default
    namespace: signalrchat-app-uat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-puller'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: signalrchat-app-prod-image-puller
  namespace: signalrchat-app-pipeline
subjects:
  - kind: ServiceAccount
    name: default
    namespace: signalrchat-app-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-puller'


