apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: signalrchat-build-and-deploy-to-dev
  namespace: signalrchat-app-pipeline
spec:
  params:
    - default: signalrchat-app
      name: APP_NAME
      type: string
    - default: 'https://github.com/troy-adianto/signalrchat.git'
      name: GIT_REPO
      type: string
    - default: main
      name: GIT_REVISION
      type: string
    - default: >-
        image-registry.openshift-image-registry.svc:5000/signalrchat-app-pipeline/signalrchat
      name: IMAGE_NAME
      type: string
    - default: .
      name: PATH_CONTEXT
      type: string
    - default: 5.0-ubi8
      name: VERSION
      type: string
    - default: 'https://github.com/troy-adianto/signalrchatyaml.git'
      name: MANIFEST_REPO
      type: string
    - default: signalrchat-app-dev
      name: NAMESPACE
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: build
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: TLSVERIFY
          value: 'false'
        - name: PATH_CONTEXT
          value: $(params.PATH_CONTEXT)
        - name: VERSION
          value: $(params.VERSION)
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: s2i-dotnet
      workspaces:
        - name: source
          workspace: workspace
    - name: deploy
      params:
        - name: SCRIPT
          value: oc rollout status deploy/$(params.APP_NAME) -n $(params.NAMESPACE)
      runAfter:
        - apply-manifests
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: sonarqube-scanner
      params:
        - name: SONAR_HOST_URL
          value: >-
            http://sonarqube-sonarqube.apps.cluster-dp894.dp894.sandbox29.opentlc.com/
        - name: SONAR_PROJECT_KEY
          value: signalrchat
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: sonarqube-scanner
      workspaces:
        - name: source
          workspace: workspace
        - name: sonar-settings
          workspace: workspace
    - name: fetch-deployment-manifest
      params:
        - name: url
          value: $(params.MANIFEST_REPO)
        - name: revision
          value: main
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: subdirectory
          value: manifest
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:55b0686bbd045c9c77820686318f8a5ff2aff06de566b067f408d27a93bf153c
        - name: userHome
          value: /tekton/home
      runAfter:
        - sonarqube-scanner
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: apply-manifests
      params:
        - name: manifest_dir
          value: manifest/manifest/dev
        - name: namespace
          value: $(params.NAMESPACE)
      runAfter:
        - fetch-deployment-manifest
        - build
      taskRef:
        kind: Task
        name: apply-manifests
      workspaces:
        - name: source
          workspace: workspace
  workspaces:
    - name: workspace
    - name: sonar-setting
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-template-signalrchat-build-and-deploy-to-dev
  namespace: signalrchat-app-pipeline
spec:
  params:
    - name: git-revision
    - name: git-commit-message
    - name: git-repo-url
    - name: git-repo-name
    - name: content-type
    - name: pusher-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        annotations:
          pipeline.openshift.io/started-by: opentlc-mgr
        generateName: signalrchat-build-and-deploy-to-dev-
        labels:
          tekton.dev/pipeline: signalrchat-build-and-deploy-to-dev
        namespace: signalrchat-app-pipeline
      spec:
        params:
          - name: APP_NAME
            value: signalrchat-app
          - name: GIT_REPO
            value: 'https://github.com/troy-adianto/signalrchat.git'
          - name: GIT_REVISION
            value: main
          - name: IMAGE_NAME
            value: >-
              image-registry.openshift-image-registry.svc:5000/signalrchat-app-pipeline/signalrchat
          - name: PATH_CONTEXT
            value: .
          - name: VERSION
            value: 5.0-ubi8
          - name: MANIFEST_REPO
            value: 'https://github.com/troy-adianto/signalrchatyaml.git'
          - name: NAMESPACE
            value: signalrchat-app-dev
        pipelineRef:
          name: signalrchat-build-and-deploy-to-dev
        workspaces:
          - name: workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
                storageClassName: gp2
                volumeMode: Filesystem
          - emptyDir: {}
            name: sonar-setting
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: signal-build-and-deploy-event-listener
  namespace: signalrchat-app-pipeline
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: ClusterTriggerBinding
          ref: github-push
      template:
        ref: trigger-template-signalrchat-build-and-deploy-to-dev
---
kind: Service
apiVersion: v1
metadata:
  name: signal-build-and-deploy-event-listener
  namespace: signalrchat-app-pipeline
spec:
  ports:
    - name: http-listener
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: http-metrics
      protocol: TCP
      port: 9000
      targetPort: 9000
  internalTrafficPolicy: Cluster
  type: ClusterIP
  selector:
    eventlistener: signal-build-and-deploy-event-listener
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: signal-build-and-deploy-event-listener
  namespace: signalrchat-app-pipeline
spec:
  to:
    kind: Service
    name: signal-build-and-deploy-event-listener
    weight: 100
  port:
    targetPort: 8080
