kind: Deployment
apiVersion: apps/v1
metadata:
  name: signalrchat-app
  labels:
    app: signalrchat-app
spec:
  replicas: 1
 template:
    spec:
      containers:
        - name: signalrchat-app
          image: image-registry.openshift-image-registry.svc:5000/signal-app/signalrchat:latest
          ports:
            - containerPort: 8080
              protocol: TCP
